app:
  log: 
    path: "logs/"
services:
  crawl:
    currency: 
      interval: 1800
      chunk: 10

mysql:
  host: 127.0.0.1
  port: 3306
  dbname: gate
  user: root
  # pwd: CVzF5VnSsJu7f6g
  pwd: 123456